package com.paicli.spec;

import com.paicli.tool.CommandExecutionResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SpecVerifierTest {

    @TempDir
    Path projectRoot;

    @Test
    void checksScopeAfterCommandVerifiersHaveFinished() throws Exception {
        WorkspaceChangeTracker tracker = new WorkspaceChangeTracker(projectRoot);
        WorkspaceChangeTracker.Baseline baseline = tracker.captureBaseline();
        SpecVerifier verifier = new SpecVerifier(projectRoot, command -> {
            write("outside.txt", "generated by verifier command");
            return CommandExecutionResult.completed(command, 0, "ok");
        });

        SpecVerifier.VerificationRun run = verifier.verify(
                spec(ChangeSpec.ScopeMode.BOUNDED, List.of("src/**"), List.of(), commandVerifier(null, null)),
                tracker,
                baseline);

        assertEquals(SpecVerifier.Status.FAIL, result(run, "VT-SCOPE").status());
        assertTrue(result(run, "VT-SCOPE").detail().contains("outside.txt"));
        assertEquals(SpecVerifier.Status.PASS, result(run, "VT-COMMAND").status());
        assertEquals(List.of("outside.txt"), run.workspaceChanges().changedFiles());
    }

    @Test
    void parsesOnlyFreshJUnitReportsAndCountsExecutedTests() throws Exception {
        write("target/surefire-reports/TEST-Stale.xml", junit(99, 0, 0, 0));
        WorkspaceChangeTracker tracker = new WorkspaceChangeTracker(projectRoot);
        WorkspaceChangeTracker.Baseline baseline = tracker.captureBaseline();
        SpecVerifier verifier = new SpecVerifier(projectRoot, command -> {
            write("target/surefire-reports/TEST-Fresh.xml", junit(3, 0, 0, 1));
            return CommandExecutionResult.completed(command, 0, "tests passed");
        });

        SpecVerifier.VerificationRun run = verifier.verify(
                spec(
                        ChangeSpec.ScopeMode.OPEN,
                        List.of(),
                        List.of(),
                        commandVerifier("target/surefire-reports/TEST-*.xml", 2)),
                tracker,
                baseline);

        SpecVerifier.VerifierResult command = result(run, "VT-COMMAND");
        assertEquals(SpecVerifier.Status.PASS, command.status());
        assertEquals(3, command.junitSummary().tests());
        assertEquals(2, command.junitSummary().executedTests());
        assertEquals(List.of("target/surefire-reports/TEST-Fresh.xml"), command.junitSummary().reports());
        assertTrue(run.workspaceChanges().changedFiles().isEmpty(), "target 是运行产物，不应进入 Scope");
    }

    @Test
    void staleJUnitReportCannotSatisfyMinimumTests() throws Exception {
        write("target/surefire-reports/TEST-Old.xml", junit(10, 0, 0, 0));
        WorkspaceChangeTracker tracker = new WorkspaceChangeTracker(projectRoot);
        WorkspaceChangeTracker.Baseline baseline = tracker.captureBaseline();
        SpecVerifier verifier = new SpecVerifier(
                projectRoot,
                command -> CommandExecutionResult.completed(command, 0, "no tests ran"));

        SpecVerifier.VerificationRun run = verifier.verify(
                spec(
                        ChangeSpec.ScopeMode.OPEN,
                        List.of(),
                        List.of(),
                        commandVerifier("target/surefire-reports/TEST-*.xml", 1)),
                tracker,
                baseline);

        assertEquals(SpecVerifier.Status.FAIL, result(run, "VT-COMMAND").status());
        assertTrue(result(run, "VT-COMMAND").detail().contains("没有本次命令"));
    }

    @Test
    void malformedJUnitAndTimeoutAreErrorsWhileExitMismatchIsFailure() throws Exception {
        WorkspaceChangeTracker tracker = new WorkspaceChangeTracker(projectRoot);
        WorkspaceChangeTracker.Baseline baseline = tracker.captureBaseline();

        SpecVerifier malformedVerifier = new SpecVerifier(projectRoot, command -> {
            write("reports/TEST-Bad.xml", "<!DOCTYPE x [<!ENTITY ext SYSTEM \"file:///etc/passwd\">]><testsuite tests=\"1\"/>");
            return CommandExecutionResult.completed(command, 0, "ok");
        });
        SpecVerifier.VerificationRun malformed = malformedVerifier.verify(
                spec(ChangeSpec.ScopeMode.OPEN, List.of(), List.of(), commandVerifier("reports/*.xml", 1)),
                tracker,
                baseline);
        assertEquals(SpecVerifier.Status.ERROR, result(malformed, "VT-COMMAND").status());

        SpecVerifier timeoutVerifier = new SpecVerifier(
                projectRoot,
                command -> CommandExecutionResult.timedOut(command, ""));
        SpecVerifier.VerificationRun timeout = timeoutVerifier.verify(
                spec(ChangeSpec.ScopeMode.OPEN, List.of(), List.of(), commandVerifier(null, null)),
                tracker,
                tracker.captureBaseline());
        assertEquals(SpecVerifier.Status.ERROR, result(timeout, "VT-COMMAND").status());

        SpecVerifier exitVerifier = new SpecVerifier(
                projectRoot,
                command -> CommandExecutionResult.completed(command, 2, "failed"));
        SpecVerifier.VerificationRun exit = exitVerifier.verify(
                spec(ChangeSpec.ScopeMode.OPEN, List.of(), List.of(), commandVerifier(null, null)),
                tracker,
                tracker.captureBaseline());
        assertEquals(SpecVerifier.Status.FAIL, result(exit, "VT-COMMAND").status());
    }

    @Test
    void authorizationDenialStopsLaterCommandVerifiers() throws Exception {
        WorkspaceChangeTracker tracker = new WorkspaceChangeTracker(projectRoot);
        AtomicInteger executions = new AtomicInteger();
        SpecVerifier verifier = new SpecVerifier(projectRoot, command -> {
            executions.incrementAndGet();
            return CommandExecutionResult.denied(
                    command,
                    CommandExecutionResult.Status.HITL_DENIED,
                    "user rejected");
        });

        SpecVerifier.VerificationRun run = verifier.verify(
                spec(
                        ChangeSpec.ScopeMode.OPEN,
                        List.of(),
                        List.of(),
                        commandVerifier("VT-FIRST", null, null),
                        commandVerifier("VT-SECOND", null, null)),
                tracker,
                tracker.captureBaseline());

        assertEquals(1, executions.get());
        assertEquals(SpecVerifier.Status.ERROR, result(run, "VT-FIRST").status());
        assertEquals(SpecVerifier.Status.ERROR, result(run, "VT-SECOND").status());
        assertTrue(result(run, "VT-SECOND").detail().contains("未运行"));
    }

    private ChangeSpec spec(
            ChangeSpec.ScopeMode mode,
            List<String> include,
            List<String> exclude,
            ChangeSpec.VerifierDefinition... extraVerifiers
    ) {
        List<ChangeSpec.VerifierDefinition> verifiers = new java.util.ArrayList<>();
        verifiers.add(new ChangeSpec.VerifierDefinition(
                "VT-SCOPE", ChangeSpec.VerifierType.PATH_SCOPE, null, null));
        verifiers.addAll(List.of(extraVerifiers));
        return new ChangeSpec(
                "paicli/change-spec/v1",
                "CHANGE-TEST",
                1,
                "test",
                new ChangeSpec.Intent("test", List.of()),
                new ChangeSpec.Scope(mode, include, exclude),
                List.of(),
                verifiers);
    }

    private ChangeSpec.VerifierDefinition commandVerifier(String reportGlob, Integer minimumTests) {
        return commandVerifier("VT-COMMAND", reportGlob, minimumTests);
    }

    private ChangeSpec.VerifierDefinition commandVerifier(
            String id,
            String reportGlob,
            Integer minimumTests
    ) {
        return new ChangeSpec.VerifierDefinition(
                id,
                ChangeSpec.VerifierType.COMMAND,
                "verify",
                new ChangeSpec.CommandExpectation(0, reportGlob, minimumTests));
    }

    private SpecVerifier.VerifierResult result(SpecVerifier.VerificationRun run, String id) {
        return run.verifierResults().stream()
                .filter(result -> result.verifierId().equals(id))
                .findFirst()
                .orElseThrow();
    }

    private String junit(int tests, int failures, int errors, int skipped) {
        return "<testsuite tests=\"" + tests + "\" failures=\"" + failures
                + "\" errors=\"" + errors + "\" skipped=\"" + skipped + "\"/>";
    }

    private void write(String relative, String content) {
        try {
            Path target = projectRoot.resolve(relative);
            Files.createDirectories(target.getParent());
            Files.writeString(target, content);
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }
}
