package com.paicli.change;

public enum ChangePermission {
    CREATE_TASK,
    READ_TASK,
    READ_EVENTS,
    READ_ARTIFACTS,
    CANCEL_DRAFT,
    RETRY_DRAFT,
    SUPPLEMENT_SPEC,
    APPROVE_SPEC,
    RECORD_HUMAN_EVIDENCE,
    APPROVE_DELIVERY,
    APPROVE_TOOL,
    MANAGE_CONNECTIONS,
    MANAGE_TOOL_POLICY,
    MANAGE_PROJECT,
    MANAGE_MEMBERS
}
